version: '3.8'

services:
  core:
    image: simulator-core:latest
    ports:
      - "50051:50051"
    networks:
      - my_network

  web:
    image: simulator-web:latest
    ports:
      - "3000:80"
    networks:
      - my_network

  envoy:
    image: envoyproxy/envoy:v1.18.3
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - core
      - web

networks:
  my_network:
    driver: bridge
