services:
  core:
    image: simulator-core:latest
    container_name: envoy-core
    ports:
      - "50051:50051"
  web:
    image: simulator-web:latest
    container_name: envoy-web
    ports:
      - "3000:80"
  envoy:
    image: envoyproxy/envoy:v1.18.3
    container_name: envoy-envoy
    ports:
      - "8080:8080"
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - core
      - web
