// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0-devel
// 	protoc        v3.12.4
// source: aura.proto

package aura

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculationType int32

const (
	CalculationType_NONE      CalculationType = 0
	CalculationType_LINEAR    CalculationType = 1
	CalculationType_QUADRATIC CalculationType = 2
)

// Enum value maps for CalculationType.
var (
	CalculationType_name = map[int32]string{
		0: "NONE",
		1: "LINEAR",
		2: "QUADRATIC",
	}
	CalculationType_value = map[string]int32{
		"NONE":      0,
		"LINEAR":    1,
		"QUADRATIC": 2,
	}
)

func (x CalculationType) Enum() *CalculationType {
	p := new(CalculationType)
	*p = x
	return p
}

func (x CalculationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CalculationType) Descriptor() protoreflect.EnumDescriptor {
	return file_aura_proto_enumTypes[0].Descriptor()
}

func (CalculationType) Type() protoreflect.EnumType {
	return &file_aura_proto_enumTypes[0]
}

func (x CalculationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CalculationType.Descriptor instead.
func (CalculationType) EnumDescriptor() ([]byte, []int) {
	return file_aura_proto_rawDescGZIP(), []int{0}
}

type Parameter int32

const (
	Parameter_NOTHING Parameter = 0
	Parameter_HP      Parameter = 1
	Parameter_PHY     Parameter = 2
	Parameter_INT     Parameter = 3
	Parameter_AGI     Parameter = 4
)

// Enum value maps for Parameter.
var (
	Parameter_name = map[int32]string{
		0: "NOTHING",
		1: "HP",
		2: "PHY",
		3: "INT",
		4: "AGI",
	}
	Parameter_value = map[string]int32{
		"NOTHING": 0,
		"HP":      1,
		"PHY":     2,
		"INT":     3,
		"AGI":     4,
	}
)

func (x Parameter) Enum() *Parameter {
	p := new(Parameter)
	*p = x
	return p
}

func (x Parameter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Parameter) Descriptor() protoreflect.EnumDescriptor {
	return file_aura_proto_enumTypes[1].Descriptor()
}

func (Parameter) Type() protoreflect.EnumType {
	return &file_aura_proto_enumTypes[1]
}

func (x Parameter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Parameter.Descriptor instead.
func (Parameter) EnumDescriptor() ([]byte, []int) {
	return file_aura_proto_rawDescGZIP(), []int{1}
}

type Occasions int32

const (
	Occasions_BATTLE    Occasions = 0
	Occasions_QUEST     Occasions = 1
	Occasions_CP_MINING Occasions = 2
)

// Enum value maps for Occasions.
var (
	Occasions_name = map[int32]string{
		0: "BATTLE",
		1: "QUEST",
		2: "CP_MINING",
	}
	Occasions_value = map[string]int32{
		"BATTLE":    0,
		"QUEST":     1,
		"CP_MINING": 2,
	}
)

func (x Occasions) Enum() *Occasions {
	p := new(Occasions)
	*p = x
	return p
}

func (x Occasions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Occasions) Descriptor() protoreflect.EnumDescriptor {
	return file_aura_proto_enumTypes[2].Descriptor()
}

func (Occasions) Type() protoreflect.EnumType {
	return &file_aura_proto_enumTypes[2]
}

func (x Occasions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Occasions.Descriptor instead.
func (Occasions) EnumDescriptor() ([]byte, []int) {
	return file_aura_proto_rawDescGZIP(), []int{2}
}

type Trigger int32

const (
	Trigger_DURING Trigger = 0
	Trigger_BEFORE Trigger = 1
)

// Enum value maps for Trigger.
var (
	Trigger_name = map[int32]string{
		0: "DURING",
		1: "BEFORE",
	}
	Trigger_value = map[string]int32{
		"DURING": 0,
		"BEFORE": 1,
	}
)

func (x Trigger) Enum() *Trigger {
	p := new(Trigger)
	*p = x
	return p
}

func (x Trigger) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Trigger) Descriptor() protoreflect.EnumDescriptor {
	return file_aura_proto_enumTypes[3].Descriptor()
}

func (Trigger) Type() protoreflect.EnumType {
	return &file_aura_proto_enumTypes[3]
}

func (x Trigger) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Trigger.Descriptor instead.
func (Trigger) EnumDescriptor() ([]byte, []int) {
	return file_aura_proto_rawDescGZIP(), []int{3}
}

type AuraEffect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuraType       uint32 `protobuf:"varint,1,opt,name=aura_type,json=auraType,proto3" json:"aura_type,omitempty"`
	EffectValue    int32  `protobuf:"varint,2,opt,name=effect_value,json=effectValue,proto3" json:"effect_value,omitempty"`
	SecondaryValue int32  `protobuf:"varint,3,opt,name=secondary_value,json=secondaryValue,proto3" json:"secondary_value,omitempty"`
	Shortage       int32  `protobuf:"varint,4,opt,name=shortage,proto3" json:"shortage,omitempty"`
	IsActive       bool   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *AuraEffect) Reset() {
	*x = AuraEffect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aura_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuraEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuraEffect) ProtoMessage() {}

func (x *AuraEffect) ProtoReflect() protoreflect.Message {
	mi := &file_aura_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuraEffect.ProtoReflect.Descriptor instead.
func (*AuraEffect) Descriptor() ([]byte, []int) {
	return file_aura_proto_rawDescGZIP(), []int{0}
}

func (x *AuraEffect) GetAuraType() uint32 {
	if x != nil {
		return x.AuraType
	}
	return 0
}

func (x *AuraEffect) GetEffectValue() int32 {
	if x != nil {
		return x.EffectValue
	}
	return 0
}

func (x *AuraEffect) GetSecondaryValue() int32 {
	if x != nil {
		return x.SecondaryValue
	}
	return 0
}

func (x *AuraEffect) GetShortage() int32 {
	if x != nil {
		return x.Shortage
	}
	return 0
}

func (x *AuraEffect) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type AuraTypeMaster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuraType         uint32             `protobuf:"varint,1,opt,name=aura_type,json=auraType,proto3" json:"aura_type,omitempty"`
	AttributeTypes   []uint32           `protobuf:"varint,2,rep,packed,name=attribute_types,json=attributeTypes,proto3" json:"attribute_types,omitempty"`
	Color            Parameter          `protobuf:"varint,3,opt,name=color,proto3,enum=aura.Parameter" json:"color,omitempty"`
	HeroType         uint32             `protobuf:"varint,4,opt,name=hero_type,json=heroType,proto3" json:"hero_type,omitempty"`
	Required         int32              `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	NumericCondition *Param             `protobuf:"bytes,6,opt,name=numeric_condition,json=numericCondition,proto3" json:"numeric_condition,omitempty"`
	Effect           *CalculationMethod `protobuf:"bytes,7,opt,name=effect,proto3" json:"effect,omitempty"`
	Secondary        *CalculationMethod `protobuf:"bytes,8,opt,name=secondary,proto3" json:"secondary,omitempty"`
	Occasions        Occasions          `protobuf:"varint,9,opt,name=occasions,proto3,enum=aura.Occasions" json:"occasions,omitempty"`
	Trigger          Trigger            `protobuf:"varint,10,opt,name=trigger,proto3,enum=aura.Trigger" json:"trigger,omitempty"`
}

func (x *AuraTypeMaster) Reset() {
	*x = AuraTypeMaster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aura_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuraTypeMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuraTypeMaster) ProtoMessage() {}

func (x *AuraTypeMaster) ProtoReflect() protoreflect.Message {
	mi := &file_aura_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuraTypeMaster.ProtoReflect.Descriptor instead.
func (*AuraTypeMaster) Descriptor() ([]byte, []int) {
	return file_aura_proto_rawDescGZIP(), []int{1}
}

func (x *AuraTypeMaster) GetAuraType() uint32 {
	if x != nil {
		return x.AuraType
	}
	return 0
}

func (x *AuraTypeMaster) GetAttributeTypes() []uint32 {
	if x != nil {
		return x.AttributeTypes
	}
	return nil
}

func (x *AuraTypeMaster) GetColor() Parameter {
	if x != nil {
		return x.Color
	}
	return Parameter_NOTHING
}

func (x *AuraTypeMaster) GetHeroType() uint32 {
	if x != nil {
		return x.HeroType
	}
	return 0
}

func (x *AuraTypeMaster) GetRequired() int32 {
	if x != nil {
		return x.Required
	}
	return 0
}

func (x *AuraTypeMaster) GetNumericCondition() *Param {
	if x != nil {
		return x.NumericCondition
	}
	return nil
}

func (x *AuraTypeMaster) GetEffect() *CalculationMethod {
	if x != nil {
		return x.Effect
	}
	return nil
}

func (x *AuraTypeMaster) GetSecondary() *CalculationMethod {
	if x != nil {
		return x.Secondary
	}
	return nil
}

func (x *AuraTypeMaster) GetOccasions() Occasions {
	if x != nil {
		return x.Occasions
	}
	return Occasions_BATTLE
}

func (x *AuraTypeMaster) GetTrigger() Trigger {
	if x != nil {
		return x.Trigger
	}
	return Trigger_DURING
}

type Param struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hp  int32 `protobuf:"varint,1,opt,name=hp,proto3" json:"hp,omitempty"`
	Phy int32 `protobuf:"varint,2,opt,name=phy,proto3" json:"phy,omitempty"`
	Int int32 `protobuf:"varint,3,opt,name=int,proto3" json:"int,omitempty"`
	Agi int32 `protobuf:"varint,4,opt,name=agi,proto3" json:"agi,omitempty"`
}

func (x *Param) Reset() {
	*x = Param{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aura_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_aura_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_aura_proto_rawDescGZIP(), []int{2}
}

func (x *Param) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Param) GetPhy() int32 {
	if x != nil {
		return x.Phy
	}
	return 0
}

func (x *Param) GetInt() int32 {
	if x != nil {
		return x.Int
	}
	return 0
}

func (x *Param) GetAgi() int32 {
	if x != nil {
		return x.Agi
	}
	return 0
}

type CalculationMethod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method      CalculationType `protobuf:"varint,1,opt,name=method,proto3,enum=aura.CalculationType" json:"method,omitempty"`
	Parameter   Parameter       `protobuf:"varint,2,opt,name=parameter,proto3,enum=aura.Parameter" json:"parameter,omitempty"`
	Coefficient float32         `protobuf:"fixed32,3,opt,name=coefficient,proto3" json:"coefficient,omitempty"`
	Intercept   int32           `protobuf:"varint,4,opt,name=intercept,proto3" json:"intercept,omitempty"`
}

func (x *CalculationMethod) Reset() {
	*x = CalculationMethod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aura_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculationMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationMethod) ProtoMessage() {}

func (x *CalculationMethod) ProtoReflect() protoreflect.Message {
	mi := &file_aura_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationMethod.ProtoReflect.Descriptor instead.
func (*CalculationMethod) Descriptor() ([]byte, []int) {
	return file_aura_proto_rawDescGZIP(), []int{3}
}

func (x *CalculationMethod) GetMethod() CalculationType {
	if x != nil {
		return x.Method
	}
	return CalculationType_NONE
}

func (x *CalculationMethod) GetParameter() Parameter {
	if x != nil {
		return x.Parameter
	}
	return Parameter_NOTHING
}

func (x *CalculationMethod) GetCoefficient() float32 {
	if x != nil {
		return x.Coefficient
	}
	return 0
}

func (x *CalculationMethod) GetIntercept() int32 {
	if x != nil {
		return x.Intercept
	}
	return 0
}

type AuraEffects struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuraEffects []*AuraEffect `protobuf:"bytes,1,rep,name=aura_effects,json=auraEffects,proto3" json:"aura_effects,omitempty"`
}

func (x *AuraEffects) Reset() {
	*x = AuraEffects{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aura_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuraEffects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuraEffects) ProtoMessage() {}

func (x *AuraEffects) ProtoReflect() protoreflect.Message {
	mi := &file_aura_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuraEffects.ProtoReflect.Descriptor instead.
func (*AuraEffects) Descriptor() ([]byte, []int) {
	return file_aura_proto_rawDescGZIP(), []int{4}
}

func (x *AuraEffects) GetAuraEffects() []*AuraEffect {
	if x != nil {
		return x.AuraEffects
	}
	return nil
}

var File_aura_proto protoreflect.FileDescriptor

var file_aura_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x75, 0x72, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75,
	0x72, 0x61, 0x22, 0xae, 0x01, 0x0a, 0x0a, 0x41, 0x75, 0x72, 0x61, 0x45, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x72, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x75, 0x72, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x22, 0xb0, 0x03, 0x0a, 0x0e, 0x41, 0x75, 0x72, 0x61, 0x54, 0x79, 0x70, 0x65,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x72, 0x61, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x75, 0x72, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0e, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x05,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x61, 0x75,
	0x72, 0x61, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x05, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x38, 0x0a, 0x11,
	0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x52, 0x10, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x2e, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52,
	0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x35, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x61, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x75, 0x72,
	0x61, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x52, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x12, 0x2d,
	0x0a, 0x09, 0x6f, 0x63, 0x63, 0x61, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x2e, 0x4f, 0x63, 0x63, 0x61, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x09, 0x6f, 0x63, 0x63, 0x61, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x27, 0x0a,
	0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d,
	0x2e, 0x61, 0x75, 0x72, 0x61, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x07, 0x74,
	0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x22, 0x4d, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x68, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x68, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x68,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x69, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x61, 0x67, 0x69, 0x22, 0xb1, 0x01, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x75,
	0x72, 0x61, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x2d, 0x0a, 0x09, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x61, 0x75, 0x72, 0x61, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x09,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x65,
	0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b,
	0x63, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x22, 0x42, 0x0a, 0x0b, 0x41, 0x75, 0x72,
	0x61, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x12, 0x33, 0x0a, 0x0c, 0x61, 0x75, 0x72, 0x61,
	0x5f, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x61, 0x75, 0x72, 0x61, 0x2e, 0x41, 0x75, 0x72, 0x61, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74,
	0x52, 0x0b, 0x61, 0x75, 0x72, 0x61, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x2a, 0x36, 0x0a,
	0x0f, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x49,
	0x4e, 0x45, 0x41, 0x52, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x51, 0x55, 0x41, 0x44, 0x52, 0x41,
	0x54, 0x49, 0x43, 0x10, 0x02, 0x2a, 0x3b, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x54, 0x48, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12,
	0x06, 0x0a, 0x02, 0x48, 0x50, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x48, 0x59, 0x10, 0x02,
	0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x54, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x47, 0x49,
	0x10, 0x04, 0x2a, 0x31, 0x0a, 0x09, 0x4f, 0x63, 0x63, 0x61, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x0a, 0x0a, 0x06, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x51,
	0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x50, 0x5f, 0x4d, 0x49, 0x4e,
	0x49, 0x4e, 0x47, 0x10, 0x02, 0x2a, 0x21, 0x0a, 0x07, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x12, 0x0a, 0x0a, 0x06, 0x44, 0x55, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x42, 0x45, 0x46, 0x4f, 0x52, 0x45, 0x10, 0x01, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x69, 0x6a, 0x6a, 0x69, 0x72, 0x69, 0x2f, 0x73,
	0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x75, 0x72, 0x61, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aura_proto_rawDescOnce sync.Once
	file_aura_proto_rawDescData = file_aura_proto_rawDesc
)

func file_aura_proto_rawDescGZIP() []byte {
	file_aura_proto_rawDescOnce.Do(func() {
		file_aura_proto_rawDescData = protoimpl.X.CompressGZIP(file_aura_proto_rawDescData)
	})
	return file_aura_proto_rawDescData
}

var file_aura_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_aura_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_aura_proto_goTypes = []interface{}{
	(CalculationType)(0),      // 0: aura.CalculationType
	(Parameter)(0),            // 1: aura.Parameter
	(Occasions)(0),            // 2: aura.Occasions
	(Trigger)(0),              // 3: aura.Trigger
	(*AuraEffect)(nil),        // 4: aura.AuraEffect
	(*AuraTypeMaster)(nil),    // 5: aura.AuraTypeMaster
	(*Param)(nil),             // 6: aura.Param
	(*CalculationMethod)(nil), // 7: aura.CalculationMethod
	(*AuraEffects)(nil),       // 8: aura.AuraEffects
}
var file_aura_proto_depIdxs = []int32{
	1, // 0: aura.AuraTypeMaster.color:type_name -> aura.Parameter
	6, // 1: aura.AuraTypeMaster.numeric_condition:type_name -> aura.Param
	7, // 2: aura.AuraTypeMaster.effect:type_name -> aura.CalculationMethod
	7, // 3: aura.AuraTypeMaster.secondary:type_name -> aura.CalculationMethod
	2, // 4: aura.AuraTypeMaster.occasions:type_name -> aura.Occasions
	3, // 5: aura.AuraTypeMaster.trigger:type_name -> aura.Trigger
	0, // 6: aura.CalculationMethod.method:type_name -> aura.CalculationType
	1, // 7: aura.CalculationMethod.parameter:type_name -> aura.Parameter
	4, // 8: aura.AuraEffects.aura_effects:type_name -> aura.AuraEffect
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_aura_proto_init() }
func file_aura_proto_init() {
	if File_aura_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aura_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuraEffect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aura_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuraTypeMaster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aura_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Param); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aura_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculationMethod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aura_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuraEffects); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aura_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aura_proto_goTypes,
		DependencyIndexes: file_aura_proto_depIdxs,
		EnumInfos:         file_aura_proto_enumTypes,
		MessageInfos:      file_aura_proto_msgTypes,
	}.Build()
	File_aura_proto = out.File
	file_aura_proto_rawDesc = nil
	file_aura_proto_goTypes = nil
	file_aura_proto_depIdxs = nil
}
