// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0-devel
// 	protoc        v3.12.4
// source: janken.proto

package janken

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hand int32

const (
	Hand_UNKNOWN  Hand = 0
	Hand_ROCK     Hand = 1
	Hand_PAPER    Hand = 2
	Hand_SCISSORS Hand = 3
)

// Enum value maps for Hand.
var (
	Hand_name = map[int32]string{
		0: "UNKNOWN",
		1: "ROCK",
		2: "PAPER",
		3: "SCISSORS",
	}
	Hand_value = map[string]int32{
		"UNKNOWN":  0,
		"ROCK":     1,
		"PAPER":    2,
		"SCISSORS": 3,
	}
)

func (x Hand) Enum() *Hand {
	p := new(Hand)
	*p = x
	return p
}

func (x Hand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hand) Descriptor() protoreflect.EnumDescriptor {
	return file_janken_proto_enumTypes[0].Descriptor()
}

func (Hand) Type() protoreflect.EnumType {
	return &file_janken_proto_enumTypes[0]
}

func (x Hand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hand.Descriptor instead.
func (Hand) EnumDescriptor() ([]byte, []int) {
	return file_janken_proto_rawDescGZIP(), []int{0}
}

type JankenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerHand Hand `protobuf:"varint,1,opt,name=player_hand,json=playerHand,proto3,enum=janken.Hand" json:"player_hand,omitempty"`
}

func (x *JankenRequest) Reset() {
	*x = JankenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_janken_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JankenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JankenRequest) ProtoMessage() {}

func (x *JankenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_janken_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JankenRequest.ProtoReflect.Descriptor instead.
func (*JankenRequest) Descriptor() ([]byte, []int) {
	return file_janken_proto_rawDescGZIP(), []int{0}
}

func (x *JankenRequest) GetPlayerHand() Hand {
	if x != nil {
		return x.PlayerHand
	}
	return Hand_UNKNOWN
}

type JankenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerHand Hand   `protobuf:"varint,1,opt,name=player_hand,json=playerHand,proto3,enum=janken.Hand" json:"player_hand,omitempty"`
	ServerHand Hand   `protobuf:"varint,2,opt,name=server_hand,json=serverHand,proto3,enum=janken.Hand" json:"server_hand,omitempty"`
	Result     string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *JankenResponse) Reset() {
	*x = JankenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_janken_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JankenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JankenResponse) ProtoMessage() {}

func (x *JankenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_janken_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JankenResponse.ProtoReflect.Descriptor instead.
func (*JankenResponse) Descriptor() ([]byte, []int) {
	return file_janken_proto_rawDescGZIP(), []int{1}
}

func (x *JankenResponse) GetPlayerHand() Hand {
	if x != nil {
		return x.PlayerHand
	}
	return Hand_UNKNOWN
}

func (x *JankenResponse) GetServerHand() Hand {
	if x != nil {
		return x.ServerHand
	}
	return Hand_UNKNOWN
}

func (x *JankenResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_janken_proto protoreflect.FileDescriptor

var file_janken_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6a, 0x61, 0x6e, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6a, 0x61, 0x6e, 0x6b, 0x65, 0x6e, 0x22, 0x3e, 0x0a, 0x0d, 0x4a, 0x61, 0x6e, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6a,
	0x61, 0x6e, 0x6b, 0x65, 0x6e, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x22, 0x86, 0x01, 0x0a, 0x0e, 0x4a, 0x61, 0x6e, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x0b, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c,
	0x2e, 0x6a, 0x61, 0x6e, 0x6b, 0x65, 0x6e, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x0a, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x12, 0x2d, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x6a, 0x61, 0x6e, 0x6b, 0x65, 0x6e, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x52, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a,
	0x36, 0x0a, 0x04, 0x48, 0x61, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x50, 0x41, 0x50, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x43, 0x49,
	0x53, 0x53, 0x4f, 0x52, 0x53, 0x10, 0x03, 0x32, 0x4c, 0x0a, 0x0d, 0x4a, 0x61, 0x6e, 0x6b, 0x65,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79,
	0x4a, 0x61, 0x6e, 0x6b, 0x65, 0x6e, 0x12, 0x15, 0x2e, 0x6a, 0x61, 0x6e, 0x6b, 0x65, 0x6e, 0x2e,
	0x4a, 0x61, 0x6e, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x6a, 0x61, 0x6e, 0x6b, 0x65, 0x6e, 0x2e, 0x4a, 0x61, 0x6e, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x69, 0x6a, 0x6a, 0x69, 0x72, 0x69, 0x2f, 0x73, 0x69, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x67, 0x6f, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6a, 0x61, 0x6e, 0x6b, 0x65, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_janken_proto_rawDescOnce sync.Once
	file_janken_proto_rawDescData = file_janken_proto_rawDesc
)

func file_janken_proto_rawDescGZIP() []byte {
	file_janken_proto_rawDescOnce.Do(func() {
		file_janken_proto_rawDescData = protoimpl.X.CompressGZIP(file_janken_proto_rawDescData)
	})
	return file_janken_proto_rawDescData
}

var file_janken_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_janken_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_janken_proto_goTypes = []interface{}{
	(Hand)(0),              // 0: janken.Hand
	(*JankenRequest)(nil),  // 1: janken.JankenRequest
	(*JankenResponse)(nil), // 2: janken.JankenResponse
}
var file_janken_proto_depIdxs = []int32{
	0, // 0: janken.JankenRequest.player_hand:type_name -> janken.Hand
	0, // 1: janken.JankenResponse.player_hand:type_name -> janken.Hand
	0, // 2: janken.JankenResponse.server_hand:type_name -> janken.Hand
	1, // 3: janken.JankenService.PlayJanken:input_type -> janken.JankenRequest
	2, // 4: janken.JankenService.PlayJanken:output_type -> janken.JankenResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_janken_proto_init() }
func file_janken_proto_init() {
	if File_janken_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_janken_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JankenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_janken_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JankenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_janken_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_janken_proto_goTypes,
		DependencyIndexes: file_janken_proto_depIdxs,
		EnumInfos:         file_janken_proto_enumTypes,
		MessageInfos:      file_janken_proto_msgTypes,
	}.Build()
	File_janken_proto = out.File
	file_janken_proto_rawDesc = nil
	file_janken_proto_goTypes = nil
	file_janken_proto_depIdxs = nil
}
